### ISSUE TITLE
Could not custom voice style

### ISSUE THREAD

**Issue by richshaw2015** [markokosticdev/cloud_text_to_speech#1]
could not use `mstts:express-as` tag to custom voice style:

`<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis"
       xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="en-US">
    <voice name="my-custom-voice">
        <mstts:express-as style="cheerful" styledegree="2">
            That'd be just amazing!
        </mstts:express-as>
    </voice>
</speak>`

**Comment by markokosticdev** [comment]
Please show me the code, to achieve it
